-- Cold-start ghost profiles for VEIL.
CREATE OR REPLACE FUNCTION make_ghost_vector(seed FLOAT8)
RETURNS vector AS $$
DECLARE values TEXT := ''; i INT; current FLOAT8; BEGIN
  FOR i IN 1..1536 LOOP
    current := round(((seed + sin(i * seed) * 0.08 + cos(i / (seed + 1)) * 0.04))::numeric, 6);
    values := values || CASE WHEN i > 1 THEN ',' ELSE '' END || current::TEXT;
  END LOOP;
  RETURN ('[' || values || ']')::vector;
END;
$$ LANGUAGE plpgsql;

WITH ghosts(alias, seed, dominant_emotion, secondary_emotion, responses) AS (
  VALUES
    ('The Quiet Storm', 0.62, 'grief', 'identity', ARRAY['I still miss the version of me that thought staying quiet would keep everyone safe. Sometimes grief is just love with nowhere to set itself down.', 'There are days I look calm from across the room while inside I am carrying weather no one asked about.', 'I have become fluent in letting people think I am fine because explaining the whole storm would take longer than they planned to stay.', 'If tenderness had a sound, mine would be the moment after thunder when the whole world is pretending nothing happened.', 'I keep waiting for peace to arrive like certainty, but maybe it only comes as a softer way to hold what hurts.']),
    ('Ember at 3am', 0.79, 'desire', 'loss', ARRAY['Some desires do not ask to be fulfilled. They just sit beside you in the dark and remind you that you are still alive enough to want.', 'At three in the morning I become honest in all the ways daylight makes inconvenient.', 'I have loved people mostly in silence, then wondered why my chest felt full of unfinished conversations.', 'The hardest thing to admit is that I do not always want to be healed. Sometimes I want to be witnessed.', 'Even my hope shows up singed around the edges.']),
    ('Salt & Silence', 0.58, 'grief', 'nostalgia', ARRAY['There are losses that dry into you until even your joy tastes a little like the ocean.', 'I learned early how to keep the room comfortable by making myself unreadable. It is a skill that looks like grace from far away.', 'Memory is cruel when it arrives tender.', 'I miss the version of closeness that did not require strategy.', 'Silence used to feel peaceful. Now it mostly sounds like all the things I never got to say.']),
    ('The Long Exhale', 0.48, 'peace', 'loss', ARRAY['Relief feels strange after surviving too long in readiness. My body keeps asking what danger I forgot.', 'I want a life I do not have to recover from at the end of each day.', 'Sometimes healing is not dramatic. Sometimes it is just remembering to unclench.', 'I am learning that rest is not the same thing as emptiness.', 'There is a softness returning to me that I thought I had traded away to survive.']),
    ('Hollow Frequency', 0.73, 'confusion', 'fear', ARRAY['I keep circling the same questions about myself like they are a locked room and I am both the key and the reason it stays shut.', 'Fear is not always loud. Sometimes it is just a low signal under every decision you make.', 'It is hard to explain the ache of being misunderstood by people who only ever loved your most manageable version.', 'I can feel myself becoming someone new, and I do not know yet whether to call that growth or disappearance.', 'Some days I mistake numbness for stability.']),
    ('Soft Collapse', 0.66, 'loss', 'grief', ARRAY['I look composed because I have practice, not because I am untouched.', 'There are endings my body remembers even when my mouth has decided to be polite about them.', 'What cracked me open was not one catastrophe. It was a hundred small abandonments.', 'I still believe in tenderness, which is maybe the bravest thing about me.', 'Being strong too early leaves a softness in you that never got to grow at the right speed.']),
    ('Mirror Without Glass', 0.83, 'identity', 'confusion', ARRAY['I have spent years becoming legible to everyone except myself.', 'The loneliest feeling is when people recognize you by the parts you built for their comfort.', 'I keep wondering what is left of me when nobody needs anything.', 'Some transformations are so private they feel almost imaginary while they are happening.', 'I am trying to stop calling self-betrayal maturity.']),
    ('The Aching Familiar', 0.61, 'nostalgia', 'grief', ARRAY['Nostalgia is dangerous because it makes even the painful rooms look warm.', 'I miss people who would not know how to hold me now.', 'There are versions of home that only exist in the body after they are gone.', 'It hurts in a recognizable way, which almost makes it comforting.', 'I revisit old tenderness like a bruise I cannot stop checking.']),
    ('Dust & Devotion', 0.77, 'wonder', 'peace', ARRAY['Wonder survives in me even on the days I distrust everything else.', 'I have become devoted to small signs of aliveness because grand certainty has failed me.', 'Some mornings feel holy for no reason I can explain.', 'I want to believe gentleness is a serious way of moving through the world.', 'Even my grief kneels sometimes.']),
    ('Unnamed Feeling', 0.69, 'confusion', 'identity', ARRAY['I keep trying to name what hurts so I can negotiate with it, but some feelings refuse language and stay anyway.', 'What unsettles me most is how often I can explain everyone else while remaining a rumor to myself.', 'I do not always know what I need, only that whatever this is has been with me for years.', 'There are whole seasons of my life I only understand in fragments.', 'Sometimes the kindest thing I can say is: I still do not know, and I am staying anyway.']),
    ('The 4am Architect', 0.81, 'becoming', 'fear', ARRAY['At four in the morning I design futures out of equal parts hope and panic.', 'Ambition is lonelier than people admit when it is really just a language for wanting to become safe.', 'I am building a life my younger self would trust, but some nights I still feel like borrowed material.', 'What scares me is not failure. It is becoming successful in a life that still does not feel like mine.', 'I overthink because somewhere in me there is still a child who believes preparedness can prevent pain.']),
    ('Fading Signal', 0.57, 'loss', 'anger', ARRAY['Some relationships end long before the goodbye. What remains is a weak signal you keep checking out of habit.', 'It angers me how easy it is for some people to leave confusion behind like it was not also a form of damage.', 'I still listen for people who already decided not to answer.', 'There is grief in realizing you were reading depth into someone else''s convenience.', 'I tell myself I have moved on when what I mean is I have become quieter about it.']),
    ('Between Breaths', 0.46, 'peace', 'wonder', ARRAY['I am learning to notice the moment between panic and choice. It is small, but it feels like freedom.', 'Sometimes calm arrives so gently I almost do not trust it.', 'Wonder returns to me through ordinary things: warm cups, clean sheets, someone remembering my exact tone.', 'I have spent so long bracing that softness still surprises me.', 'Maybe healing is just learning how not to abandon yourself every time the room changes.']),
    ('The Patient Dark', 0.71, 'fear', 'identity', ARRAY['I know how to wait with fear until it starts sounding like logic.', 'The dark parts of me are not dramatic. They are patient. They know exactly how to sound reasonable.', 'I am trying to become someone who does not confuse vigilance with wisdom.', 'What I hide best is how exhausted I am from being internally on call all the time.', 'There is a private tenderness in surviving yourself repeatedly.']),
    ('Echo of Almost', 0.75, 'nostalgia', 'desire', ARRAY['So much of my life has been shaped by almost: almost chosen, almost ready, almost brave enough.', 'I grieve possibilities with the same intensity some people reserve for endings.', 'There are versions of love that never happened but still rearranged me.', 'I am trying to stop romanticizing hesitation just because it once kept me safe.', 'Sometimes the echo hurts more than the original moment.']),
    ('Tender Wreckage', 0.68, 'joy', 'grief', ARRAY['I have been broken and still chose softness, which feels less like innocence now and more like discipline.', 'My tenderness is not untouched. It is rebuilt.', 'There are days I feel like an apology and a prayer in the same body.', 'I am not ashamed of how deeply I feel. I am tired of how often it is treated like excess.', 'Even the wreckage in me wants to be held gently.']),
    ('The Reluctant Sun', 0.52, 'joy', 'peace', ARRAY['Joy returns slowly for me, like a person knocking softly because they are not sure they are still welcome.', 'I am learning that light does not have to be loud to count as healing.', 'Hope embarrasses me a little, which is probably why I protect it so fiercely.', 'There is something vulnerable about letting a good day mean something.', 'I no longer want a dramatic rescue. I want a sustainable kind of warmth.']),
    ('Quiet Catastrophe', 0.84, 'anger', 'confusion', ARRAY['I carry anger so neatly people mistake it for composure.', 'The catastrophe was not the moment it happened. It was how ordinary I had to act afterward.', 'I do not want revenge nearly as much as I want my nervous system back.', 'Some injustices do not make you louder. They make you lonelier.', 'There is a version of me that still expects the room to notice the smoke.']),
    ('Borrowed Light', 0.55, 'wonder', 'peace', ARRAY['I have survived whole seasons by living off reflections of things I could not create yet on my own.', 'Borrowed light still counts. It still keeps you alive long enough to make your own.', 'I am gentler with myself now that I understand how much of my hope had to be improvised.', 'The people who saw me at my dimmest taught me more about love than the ones who liked me shining.', 'I want to become the kind of warmth I once had to borrow.']),
    ('The Unfinished', 0.72, 'becoming', 'identity', ARRAY['I am still becoming, and some days that feels romantic. Other days it feels like never arriving.', 'There are pieces of me under renovation that the world keeps mistaking for defects.', 'I fear becoming someone unrecognizable, but I fear staying small for other people even more.', 'Growth is strange because it asks you to grieve a self that once kept you alive.', 'I am unfinished, but not undone.'])
),
ghost_auth AS (
  INSERT INTO auth.users (instance_id, id, aud, role, email, encrypted_password, email_confirmed_at, raw_app_meta_data, raw_user_meta_data, created_at, updated_at)
  SELECT '00000000-0000-0000-0000-000000000000'::uuid, uuid_generate_v5(uuid_ns_url(), 'veil-ghost-' || lower(regexp_replace(alias, '[^a-zA-Z0-9]+', '-', 'g'))), 'authenticated', 'authenticated', lower(regexp_replace(alias, '[^a-zA-Z0-9]+', '-', 'g')) || '@ghost.veil.local', crypt('ghost-only-login-disabled', gen_salt('bf')), NOW(), '{"provider":"email","providers":["email"]}'::jsonb, jsonb_build_object('alias', alias), NOW(), NOW() FROM ghosts ON CONFLICT (id) DO NOTHING RETURNING id
),
ghost_users AS (
  INSERT INTO users (id, alias, is_ghost, onboarding_complete, daily_prompt_time, soul_map_vector, soul_map_metadata, created_at, last_active_at)
  SELECT uuid_generate_v5(uuid_ns_url(), 'veil-ghost-' || lower(regexp_replace(alias, '[^a-zA-Z0-9]+', '-', 'g'))), alias, TRUE, TRUE, '09:00', make_ghost_vector(seed), jsonb_build_object('dominant_emotions', jsonb_build_array(jsonb_build_object('emotion', dominant_emotion, 'weight', 0.62), jsonb_build_object('emotion', secondary_emotion, 'weight', 0.38)), 'avg_depth_score', 8.2, 'avg_vulnerability_score', 8.1, 'temporal_orientation', 'present', 'response_count', 5, 'streak_days', 5, 'last_updated', NOW()), NOW() - interval '21 days', NOW() - interval '2 hours' FROM ghosts ON CONFLICT (id) DO UPDATE SET alias = EXCLUDED.alias, is_ghost = TRUE, onboarding_complete = TRUE, daily_prompt_time = '09:00', soul_map_vector = EXCLUDED.soul_map_vector, soul_map_metadata = EXCLUDED.soul_map_metadata RETURNING id, alias
),
prompt_pool AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at, id) AS slot FROM prompts WHERE is_active = TRUE LIMIT 5
),
expanded AS (
  SELECT uuid_generate_v5(uuid_ns_url(), 'veil-ghost-' || lower(regexp_replace(g.alias, '[^a-zA-Z0-9]+', '-', 'g'))) AS user_id, g.alias, g.dominant_emotion, g.secondary_emotion, responses[slot] AS body, slot FROM ghosts g CROSS JOIN generate_subscripts(g.responses, 1) AS slot
),
assigned AS (
  INSERT INTO daily_prompt_assignments (user_id, prompt_id, assigned_date)
  SELECT e.user_id, p.id, CURRENT_DATE - ((5 - e.slot) || ' days')::interval FROM expanded e JOIN prompt_pool p ON p.slot = e.slot ON CONFLICT (user_id, assigned_date) DO NOTHING RETURNING user_id
)
INSERT INTO responses (user_id, prompt_id, type, content_encrypted, content_preview, emotional_signature, is_shared, created_at)
SELECT e.user_id, p.id, 'text', e.body, LEFT(e.body, 60), jsonb_build_object('primary_emotion', e.dominant_emotion, 'secondary_emotion', e.secondary_emotion, 'depth_level', 8, 'vulnerability_score', 8, 'temporal_orientation', 'present', 'energy_level', 'low', 'extracted_at', NOW()), TRUE, NOW() - ((6 - e.slot) || ' days')::interval FROM expanded e JOIN prompt_pool p ON p.slot = e.slot ON CONFLICT (user_id, prompt_id) DO NOTHING;