INSERT INTO prompts (text, category, difficulty_level) VALUES
('What loss are you still carrying that others have forgotten about?', 'grief', 4),
('Describe something that ended before you were ready.', 'grief', 3),
('What ordinary thing secretly astonishes you?', 'wonder', 2),
('Describe a moment when the world felt larger than usual.', 'wonder', 3),
('What do you pretend not to care about?', 'identity', 4),
('Describe a version of yourself you quietly abandoned.', 'identity', 5),
('What label do people give you that feels slightly wrong?', 'identity', 3),
('What do you want that you are ashamed to want?', 'desire', 5),
('What would you do if no one was watching and no one would ever know?', 'desire', 4),
('What are you most afraid of becoming?', 'fear', 5),
('What do you avoid thinking about before you sleep?', 'fear', 4),
('What small thing made today more bearable?', 'joy', 1),
('Describe a moment of joy you have never told anyone about.', 'joy', 3),
('What do you miss that no longer exists?', 'loss', 3),
('What did you used to believe that you wish were still true?', 'loss', 4),
('Who are you becoming that scares you a little?', 'becoming', 5),
('What is something about you that is still unfinished?', 'becoming', 3),
('What place exists only in your memory now?', 'nostalgia', 3),
('Describe a sound from your childhood that no one else would remember.', 'nostalgia', 4),
('What injustice do you carry quietly?', 'anger', 4),
('What do you wish you had said?', 'anger', 3),
('When do you feel most like yourself?', 'peace', 2),
('Describe a moment when everything felt exactly right.', 'peace', 2),
('What do you not understand about yourself?', 'confusion', 4),
('What question keeps returning to you without an answer?', 'confusion', 3),
('If your silence could speak, what would it say right now?', 'identity', 5),
('What do you wish someone had noticed about you today?', 'desire', 3),
('Describe a time you felt completely invisible.', 'grief', 4),
('What are you in the middle of that no one knows about?', 'becoming', 4),
('What would the kindest version of you say to you right now?', 'peace', 2);
