ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_ghost BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE connections
  ADD COLUMN IF NOT EXISTS ghost_user_messages INT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS ghost_reply_scheduled_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ghost_last_auto_reply_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ghost_has_withdrawn BOOLEAN NOT NULL DEFAULT FALSE;
